"""Add data_source column to Event table

Revision ID: 040f266ee58e
Revises: 2d515bb98110
Create Date: 2025-04-01 12:44:17.123535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040f266ee58e'
down_revision = '2d515bb98110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('data_source', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'data_source')
    # ### end Alembic commands ###
