"""Add EventMetricsLog table for time-series analytics

Revision ID: 2d515bb98110
Revises: fa6e8b963ce4
Create Date: 2025-03-22 14:19:34.112243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d515bb98110'
down_revision = 'fa6e8b963ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_metrics_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_date', 'event_metrics_log', ['event_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_event_date', table_name='event_metrics_log')
    op.drop_table('event_metrics_log')
    # ### end Alembic commands ###
