"""Add track_name, artist, artwork_url, and duration to ListeningHistory

Revision ID: 427cfec8259b
Revises: d31da9a366a2
Create Date: 2025-03-06 20:13:02.980323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427cfec8259b'
down_revision = 'd31da9a366a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listening_history', sa.Column('track_name', sa.String(length=256), nullable=True))
    op.add_column('listening_history', sa.Column('artist', sa.String(length=256), nullable=True))
    op.add_column('listening_history', sa.Column('artwork_url', sa.String(length=512), nullable=True))
    op.add_column('listening_history', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listening_history', 'duration')
    op.drop_column('listening_history', 'artwork_url')
    op.drop_column('listening_history', 'artist')
    op.drop_column('listening_history', 'track_name')
    # ### end Alembic commands ###
