"""added registration fields to user model

Revision ID: 599493ffa261
Revises: 6f0ab9cced38
Create Date: 2025-03-11 10:49:56.848609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599493ffa261'
down_revision = '6f0ab9cced38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('store_listening_history', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'store_listening_history')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
