"""Added profile_image_url, country, and followers columns to User model

Revision ID: 68fa253c65e9
Revises: c6b94292a105
Create Date: 2025-03-12 16:35:30.589613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68fa253c65e9'
down_revision = 'c6b94292a105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image_url', sa.String(length=512), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('followers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'followers')
    op.drop_column('user', 'country')
    op.drop_column('user', 'profile_image_url')
    # ### end Alembic commands ###
