"""Add display_name field to User model

Revision ID: 6f0ab9cced38
Revises: 66790677db31
Create Date: 2025-03-07 16:53:12.095349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0ab9cced38'
down_revision = '66790677db31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'display_name')
    # ### end Alembic commands ###
