"""add details to event

Revision ID: 752aac1b7e8a
Revises: b86f1497c327
Create Date: 2025-03-14 16:14:41.802977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752aac1b7e8a'
down_revision = 'b86f1497c327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('details', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'details')
    # ### end Alembic commands ###
