"""Added targeting fields to Event model

Revision ID: b27f281f9da9
Revises: b6efac34849e
Create Date: 2025-03-13 13:15:38.113876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b27f281f9da9'
down_revision = 'b6efac34849e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('target_country', sa.String(length=64), nullable=True))
    op.add_column('event', sa.Column('target_genre_interest', sa.String(length=256), nullable=True))
    op.add_column('event', sa.Column('target_artist_interest', sa.String(length=256), nullable=True))
    op.add_column('event', sa.Column('listening_threshold', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('target_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'target_roles')
    op.drop_column('event', 'listening_threshold')
    op.drop_column('event', 'target_artist_interest')
    op.drop_column('event', 'target_genre_interest')
    op.drop_column('event', 'target_country')
    # ### end Alembic commands ###
