"""added status and is_sponsored fields to Event model

Revision ID: b6efac34849e
Revises: 68fa253c65e9
Create Date: 2025-03-13 10:11:13.252811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6efac34849e'
down_revision = '68fa253c65e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('status', sa.String(length=64), nullable=True))
    op.add_column('event', sa.Column('is_sponsored', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'is_sponsored')
    op.drop_column('event', 'status')
    # ### end Alembic commands ###
