"""Add user_id and image to Event model

Revision ID: c6b94292a105
Revises: 81d87e09b128
Create Date: 2025-03-11 19:26:58.126033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b94292a105'
down_revision = '81d87e09b128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('url', sa.String(length=512), nullable=True))
    op.add_column('event', sa.Column('image', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'image')
    op.drop_column('event', 'url')
    op.drop_column('event', 'user_id')
    # ### end Alembic commands ###
