"""add updated models for Music Re-Wrapped

Revision ID: d31da9a366a2
Revises: 3bd46f6c5aa9
Create Date: 2025-03-06 16:29:05.933452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd31da9a366a2'
down_revision = '3bd46f6c5aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_integration_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=128), nullable=True),
    sa.Column('request_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concert_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('promoter_info', sa.String(length=256), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aggregated_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('top_tracks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_artists', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('genre_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('listening_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.String(length=128), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('user', sa.Column('role', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('oauth_token', sa.String(length=512), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'oauth_token')
    op.drop_column('user', 'role')
    op.drop_table('user_preference')
    op.drop_table('listening_history')
    op.drop_table('aggregated_stats')
    op.drop_table('concert_event')
    op.drop_table('api_integration_log')
    # ### end Alembic commands ###
