"""add promoter_id to event

Revision ID: e59356a1cd64
Revises: b27f281f9da9
Create Date: 2025-03-13 19:36:38.042946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59356a1cd64'
down_revision = 'b27f281f9da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('promoter_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'promoter_id')
    # ### end Alembic commands ###
