"""Add genre column to ListeningHistory

Revision ID: e7dba4d02736
Revises: 427cfec8259b
Create Date: 2025-03-06 20:19:15.516686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7dba4d02736'
down_revision = '427cfec8259b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listening_history', sa.Column('genre', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listening_history', 'genre')
    # ### end Alembic commands ###
