"""Add views, saves, and engagement to Event model

Revision ID: fa6e8b963ce4
Revises: 752aac1b7e8a
Create Date: 2025-03-22 13:31:41.098758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6e8b963ce4'
down_revision = '752aac1b7e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('saves', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('engagement', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'engagement')
    op.drop_column('event', 'saves')
    op.drop_column('event', 'views')
    # ### end Alembic commands ###
