name: ci-cd pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: cache docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: build backend image
        run: |
          docker build -f Dockerfile.backend -t music-rewrapped-backend .

      - name: build celery image
        run: |
          docker build -f Dockerfile.celery -t music-rewrapped-celery .

      - name: build frontend image
        run: |
          docker build -f client/Dockerfile -t music-rewrapped-frontend .

      - name: run backend migrations
        run: |
          docker run --rm \
            -e DATABASE_URL=postgresql+psycopg://postgres:password@localhost:5432/test_db \
            -e REDIS_URL=redis://localhost:6379/0 \
            music-rewrapped-backend \
            flask db upgrade
        #~ note: if update migrations locally, ensure postgres container is running

      - name: run backend integration tests
        run: |
          docker run --rm \
            -e DATABASE_URL=postgresql+psycopg://postgres:password@localhost:5432/test_db \
            -e REDIS_URL=redis://localhost:6379/0 \
            music-rewrapped-backend \
            pytest tests/integration
        #~ ensure have tests/integration available in your codebase

      - name: run frontend tests
        run: |
          docker run --rm music-rewrapped-frontend npm run test
        #~ if client tests exist, adjust command accordingly